services:
  opentofu:
    profiles: [dummy]
    network_mode: bridge
    image: ghcr.io/opentofu/opentofu:1.9.0
    environment:
      - TF_LOG
      - TF_CLI_ARGS
      # inherit AWS auth
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
    volumes:
      - .:/workspace
      # access host's aws config
      - ${HOME:-${USERPROFILE:-}}/.aws:/root/.aws
    working_dir: /workspace
