services:
  opentofu:
    profiles: [dummy]
    network_mode: bridge
    image: ghcr.io/opentofu/opentofu:1.9.0
    environment:
      - TF_LOG
      - TF_CLI_ARGS
    volumes:
      - .:/workspace
      # access host's gcloud authentication
      - ${CLOUDSDK_CONFIG:-${APPDATA:-${HOME:-}/.config}/gcloud}:/root/.config/gcloud
    working_dir: /workspace
