services:
  terraform:
    profiles: [dummy]
    network_mode: bridge
    image: hashicorp/terraform:1.9.4
    environment:
      - TF_LOG
      - CLOUDSDK_CORE_PROJECT
    volumes:
      - .:/workspace
      # access host's gcloud authentication
      - ${CLOUDSDK_CONFIG:-${APPDATA:-${HOME:-}/.config}/gcloud}:/root/.config/gcloud
    working_dir: /workspace
