version: '3'
services:
  terraform:
    profiles: [dummy]
    network_mode: bridge
    image: hashicorp/terraform:1.7.5
    environment:
      - TF_LOG
      # inherit GCP configuration
      - CLOUDSDK_CORE_PROJECT
      # inherit AWS auth
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
    volumes:
      - .:/workspace
    working_dir: /workspace
